//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wonderland.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friends
    {
        public int FriendsId { get; set; }
        public int UserFK { get; set; }
        public int FriendFK { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
