//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wonderland.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        public int PostId { get; set; }
        public string Sequence { get; set; }
        public string ImageURL { get; set; }
        public string Weather { get; set; }
        public string Location { get; set; }
        public int UserFK { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lng { get; set; }
    
        public virtual User User { get; set; }
    }
}
